### PR TITLE
Add support for pools

### LINKED ISSUE #37: Support 'pools'
Can support for configuring 'pools' be added?

Putting a pool in the server list only adds one server, whereas we'd quite like chrony to add multiple servers from the pool automatically.

### PR DESCRIPTION
**Pull request by giggsey**
Fixes #37

### CODE REVIEW

**Comment by giggsey** [comment]
I'm not sure why these tests are failing:

```
rspec './spec/classes/init_spec.rb[1:2:3]' # chrony on redhat with params should contain File[/etc/chrony/chrony.conf] with content =~ /^pool 0.pool.ntp.org iburst$/
rspec './spec/classes/init_spec.rb[1:2:4]' # chrony on redhat with params should contain File[/etc/chrony/chrony.conf] with content =~ /^pool 1.pool.ntp.org iburst$/
```

If I run it through Puppet directly, it's writing those lines. Probably something basic, but I have no experience with rspec.

**Comment by aboe76** [comment]
@giggsey rspec is looking at the wrong file > /etc/chrony/chrony.conf instead of /etc/chrony.conf

**Comment by giggsey** [comment]
:man_facepalming: Thanks @aboe76 - I've force pushed the commit again with it fixed.

**Comment by aboe76** [comment]
@giggsey thanks for this.

**Comment by aboe76** [comment]
Will try to make some time in the weekend to create a new package for the forge.

**Comment by giggsey** [comment]
Hi @aboe76, any chance of a new tag?

**Comment by aboe76** [comment]
@giggsey ow oops, forgot about that...

**Comment by vchepkov** [comment]
Ideally, addition of a new optional parameters would not modify a configuration file by adding an empty line and causing service to be restarted for no reasons.

**Comment by kenyon** [comment]
This change missed an update to README.md.

**Pull request merged**
