### PR TITLE
add log_options for logging support

### PR DESCRIPTION
**Pull request by johnwarburton**
Hello

I'd like to add support for logging options for the [log directive](https://chrony.tuxfamily.org/manual.html#log-directive) for Debian and RedHat

Thanks

John

### CODE REVIEW

**Comment by johnwarburton** [comment]
Thanks! Any chance this would be in a new version on the forge as well?

**Comment by johnwarburton** [comment]
Hello - could you please merge? I have another PR ready to go to add more functionality (peers and setting stratum)

Thanks
John

**Comment by wmoore28** [comment]
I ended up adding log_options as well.  If this is getting merged, I'll start from there for my addition of initstepslew.

**Comment by johnwarburton** [comment]
Thanks!

**Pull request merged**
