### PR TITLE
support for peers, variable local stratum, SUSE 12

### PR DESCRIPTION
**Pull request by johnwarburton**
Hello, please find PR which supports peers, variable local stratum, SUSE 12. 

In use in production

### CODE REVIEW

**Comment by aboe76** [comment]
will create a new package for the forge this weekend, please ping me if I forget...

**Comment by johnwarburton** [comment]
Thanks very much

**Comment by johnwarburton** [comment]
Hi Niels

I see the new version of chrony on the forge, but it is missing the contents of this PR! Can you please cut another version?

Thanks

John

**Comment by aboe76** [comment]
@johnwarburton done.

**Comment by johnwarburton** [comment]
Hi Niels

The forge is still not updated. Is it related to https://github.com/aboe76/puppet-chrony/commit/5751e10469bd281b268d569baee55b909ecf8bb8?

**Comment by aboe76** [comment]
yes should be updated now with version 0.2.3 fresh clone from git.

**Comment by johnwarburton** [comment]
Thanks Niels - got it!

**Pull request merged**
